# Site settings
title: Ramesh Mahadevan
subtitle: "PMP,ITIL EXPERT,SIXSIGMA BB,AGILE COACH(CSM)"
email: youremailaddress@gmail.com
description: "A  Post Graduate with PG diploma in HRM , a Muiti -Dimensional Professional (L&D/Project Management/Service Management) with  20 years of rich IT industry experience. 
After a diploma in Computers jumped into the big IT Ocean. Sailed through almost all the stages of the Software development from requirement to Implementation. 
Achieved industry relevant Credentials PMP , ITIL V3 Expert ,Six Sigma and Agile CSM. These certifications and Models provide the oriented approach to the problem resolution at my work. Very passionate about Coaching project managers.PMI India Champion tag helps in advocating the Project Management within the project management community. "
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rameshmahadevan.github.io" # the base hostname & protocol for your site
author:
street_address: 4b, Prem Nagar, Saligramam
city: Chennai
state: Tamil Nadu
zip_code: 600093
country: India
phone: +91 9884716535

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown

sass:
  style: compressed
